### ISSUE TITLE
About the package 'datasets'

### ISSUE THREAD

**Issue by ZorionHu** [SeekingDream/NICGSlowDown#1]
When I bash 'gpu4.sh' and  there was no module named 'datasets'. Then  I installed 'datasets' but the following error was encountered.

Traceback (most recent call last):                                                                                    
  File "loss_impact.py", line 10, in <module>                                                                        
    from utils import *                                                                                               
  File "/data/xxx/NICGSlowDown/utils.py", line 12, in <module>                                                
    from datasets import CaptionDataset                                                                               
ImportError: cannot import name 'CaptionDataset' from 'datasets' 

So, do you define the package yourself or call an off-the-shelf one, and can you provide a list of the packages used?

**Comment by SeekingDream** [comment]
Thank your for your comments. I update the file datasets.py
https://github.com/SeekingDream/NICGSlowDown/blob/main/datasets.py
Let me know if there are any other issues.

**Comment by ZorionHu** [comment]
After I added the file datasets.py, new issues have emerged.

FileNotFoundError: [Errno 2] No such file or directory: 'model_weight/coco/BEST_coco_mobilenet_rnn.pth.tar'

So could you provide the following documents and tell me how to use them?
    'BEST_flickr8k_googlenet_rnn.pth.tar', 'BEST_flickr8k_resnext_lstm.pth.tar', 'BEST_coco_mobilenet_rnn.pth.tar' and 'BEST_coco_resnet_lstm.pth.tar',

**Comment by SeekingDream** [comment]
These are trained image caption neural networks. You can train them from scratch using the ``train.py``.
Maybe you also need to download the datasets: [coco](https://cocodataset.org/#home) and [flickr8k](https://www.kaggle.com/adityajn105/flickr8k) for model training and experiments. After downloading the datasets, you need to ``use create_input_files`` in utils.py to create the dataset.
For more details about training the image caption neural networks, you can follow the [tutorial](https://github.com/sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning). 
If you need our pre-trained model, please let me know.

**Comment by SeekingDream** [comment]
[model weights](https://drive.google.com/file/d/1Ug9P0lpMD954Whe2T9U5nlwbIWLPGyGp/view?usp=sharing) provides our pre-trained image caption neural networks under attack.

**Comment by ZorionHu** [comment]
Thanks for your help, the problem about the dataset has been solved.
